"""Installer tests use a temporary home and never modify the real installation."""
import os
from pathlib import Path
import subprocess
import tarfile
import tempfile
import unittest
import package


class PackagingTests(unittest.TestCase):
    def test_linux_install_and_uninstall_preserve_config(self):
        with tempfile.TemporaryDirectory() as temp:
            root = Path(temp)
            binary = root / "binary"
            binary.write_text("#!/bin/sh\nexit 0\n")
            archive, = package.package("x86_64-unknown-linux-gnu", binary, root / "dist")
            extracted = root / "release"
            with tarfile.open(archive) as tar:
                self.assertEqual(tar.getmember("kbmouse").mode, 0o755)
                tar.extractall(extracted)  # Archive was just generated by this test.
            home = root / "home with spaces"
            config = home / ".config/kbmouse/config.toml"
            config.parent.mkdir(parents=True)
            config.write_text('leader = "capslock"\n')
            env = dict(os.environ, HOME=str(home), XDG_DATA_HOME=str(home / ".local/share"))
            subprocess.run(["sh", str(extracted / "install.sh")], env=env, check=True)
            installed = home / ".local/lib/kbmouse/kbmouse"
            self.assertEqual(installed.read_bytes(), binary.read_bytes())
            self.assertEqual((home / ".local/bin/kbmouse").resolve(), installed.resolve())
            desktop = home / ".local/share/applications/kbmouse.desktop"
            self.assertIn(f'Exec="{installed}"', desktop.read_text())
            subprocess.run(["sh", str(home / ".local/lib/kbmouse/uninstall.sh")], env=env, check=True)
            self.assertFalse(installed.exists())
            self.assertFalse(desktop.exists())
            self.assertTrue(config.exists())

    def test_unknown_target_rejected(self):
        with self.assertRaises(ValueError):
            package.package("unsupported", Path("none"), Path("none"))


if __name__ == "__main__":
    unittest.main()
